application: application-id  #get from your google app engine when you create an application.
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
static_dir: static

- url: /.*
script: main.py